# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-05-21 13:40:27
"""
import arcpy

def RCLmerge():  # RCLmerge

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    UTRANS_Roads_Edit_Simple = "UTRANS.Roads_Edit.Simple"

    # Process: MakeFL FwyLvl2 (Make Feature Layer) (management)
    FL_FwyLvl2 = "FL_FwyLvl2"
    arcpy.management.MakeFeatureLayer(in_features=UTRANS_Roads_Edit_Simple, out_layer=FL_FwyLvl2, where_clause="VERT_LEVEL IN ('2') And (DOT_FCLASS IN ('Interstate', 'Other Freeway') Or DOT_RTNAME LIKE '%C%' Or DOT_RTNAME LIKE '%R%') And (COUNTY_L IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045') Or COUNTY_R IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045'))")

    # Process: Dissolve FwysLvl2 (Dissolve) (management)
    DisFwysLvl2 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel2_Dissolve"
    arcpy.management.Dissolve(in_features=FL_FwyLvl2, out_feature_class=DisFwysLvl2, multi_part="MULTI_PART")

    # Process: MP2S FwysLvl2 (Multipart To Singlepart) (management)
    MP2SFwyLvl2 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel2_MP2SP"
    arcpy.management.MultipartToSinglepart(in_features=DisFwysLvl2, out_feature_class=MP2SFwyLvl2)

    # Process: MakeFL All (Make Feature Layer) (management)
    FL_All = "FL_FwyALL"
    arcpy.management.MakeFeatureLayer(in_features=UTRANS_Roads_Edit_Simple, out_layer=FL_All, where_clause="VERT_LEVEL IN ('0', '1', '2', '3') And (DOT_FCLASS IN ('Interstate', 'Other Freeway') Or DOT_RTNAME LIKE '%C%' Or DOT_RTNAME LIKE '%R%' Or DOT_FCLASS IN ('Local', 'Major Collector', 'Minor Arterial', 'Minor Collector', 'Principal Arterial')) And (COUNTY_L IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045') Or COUNTY_R IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045'))")

    # Process: Feature Vertices To Points All (Feature Vertices To Points) (management)
    FWYAllLevels_FV2PEndpoints = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYAllLevels_FV2PEndpoints"
    arcpy.management.FeatureVerticesToPoints(in_features=FL_All, out_feature_class=FWYAllLevels_FV2PEndpoints, point_location="BOTH_ENDS")

    # Process: Spatial Join to Get Concuurent Point Count (Spatial Join) (analysis)
    FWY_FV2PEndpointsCount = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWY_FV2PEndpointsCount"
    arcpy.analysis.SpatialJoin(target_features=FWYAllLevels_FV2PEndpoints, join_features=FWYAllLevels_FV2PEndpoints, out_feature_class=FWY_FV2PEndpointsCount, field_mapping="", search_radius="1 Meters")

    # Process: Make Feature Layer 1 or 3+ Points (Make Feature Layer) (management)
    FWY_FV2PEndpointsCount_3Plus = "FWY_FV2PEndpointsCount_3Plus"
    arcpy.management.MakeFeatureLayer(in_features=FWY_FV2PEndpointsCount, out_layer=FWY_FV2PEndpointsCount_3Plus, where_clause="Join_Count >= 3")

    # Process: ResplitFwyLvl2 (Split Line at Point) (management)
    SpliAtPointFwyLvl2 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel2_Resplit"
    arcpy.management.SplitLineAtPoint(in_features=MP2SFwyLvl2, point_features=FWY_FV2PEndpointsCount_3Plus, out_feature_class=SpliAtPointFwyLvl2, search_radius="0.1 Meters")

    # Process: MakeFL FwyLvl3 (Make Feature Layer) (management)
    FL_FwyLvl3 = "FL_FwyLvl3"
    arcpy.management.MakeFeatureLayer(in_features=UTRANS_Roads_Edit_Simple, out_layer=FL_FwyLvl3, where_clause="VERT_LEVEL IN ('3') And (DOT_FCLASS IN ('Interstate', 'Other Freeway') Or DOT_RTNAME LIKE '%C%' Or DOT_RTNAME LIKE '%R%') And (COUNTY_L IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045') Or COUNTY_R IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045'))")

    # Process: Dissolve FwysLvl3 (Dissolve) (management)
    DisFwysLvl3 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel3_Dissolve"
    arcpy.management.Dissolve(in_features=FL_FwyLvl3, out_feature_class=DisFwysLvl3, multi_part="MULTI_PART")

    # Process: MP2S FwysLvl3 (Multipart To Singlepart) (management)
    MP2SFwyLv3 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel3_MP2SP"
    arcpy.management.MultipartToSinglepart(in_features=DisFwysLvl3, out_feature_class=MP2SFwyLv3)

    # Process: ResplitFwyLvl3 (Split Line at Point) (management)
    SpliAtPointFwyLvl3 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel3_Resplit"
    arcpy.management.SplitLineAtPoint(in_features=MP2SFwyLv3, point_features=FWY_FV2PEndpointsCount_3Plus, out_feature_class=SpliAtPointFwyLvl3, search_radius="0.1 Meters")

    # Process: MakeFL FwyLvl1 (Make Feature Layer) (management)
    FL_FwyLvl1 = "FL_FwyLvl1"
    arcpy.management.MakeFeatureLayer(in_features=UTRANS_Roads_Edit_Simple, out_layer=FL_FwyLvl1, where_clause="VERT_LEVEL IN ('1') And (DOT_FCLASS IN ('Interstate', 'Other Freeway') Or DOT_RTNAME LIKE '%C%' Or DOT_RTNAME LIKE '%R%') And (COUNTY_L IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045') Or COUNTY_R IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045'))")

    # Process: Dissolve FwysLvl1 (Dissolve) (management)
    DisFwysLvl1 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel1_Dissolve"
    arcpy.management.Dissolve(in_features=FL_FwyLvl1, out_feature_class=DisFwysLvl1, multi_part="MULTI_PART")

    # Process: MP2S FwysLvl1 (Multipart To Singlepart) (management)
    MP2SFwyLv1 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel1_MP2SP"
    arcpy.management.MultipartToSinglepart(in_features=DisFwysLvl1, out_feature_class=MP2SFwyLv1)

    # Process: ResplitFwyLvl1 (Split Line at Point) (management)
    SpliAtPointFwyLvl1 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel1_Resplit"
    arcpy.management.SplitLineAtPoint(in_features=MP2SFwyLv1, point_features=FWY_FV2PEndpointsCount_3Plus, out_feature_class=SpliAtPointFwyLvl1, search_radius="1 Meters")

    # Process: MakeFL SurfLvl2 (Make Feature Layer) (management)
    FL_SurfLvl2 = "FL_SurfLvl2"
    arcpy.management.MakeFeatureLayer(in_features=UTRANS_Roads_Edit_Simple, out_layer=FL_SurfLvl2, where_clause="VERT_LEVEL NOT IN ('0', '1', '3') And DOT_FCLASS IN ('Local', 'Major Collector', 'Minor Arterial', 'Minor Collector', 'Principal Arterial') And (COUNTY_L IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045') Or COUNTY_R IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045'))")

    # Process: Dissolve SurfLvl2 (Dissolve) (management)
    SurfLvl2_Dissolve = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl2_Dissolve"
    arcpy.management.Dissolve(in_features=FL_SurfLvl2, out_feature_class=SurfLvl2_Dissolve, multi_part="MULTI_PART")

    # Process: MP2S SurfLvl2 (Multipart To Singlepart) (management)
    MP2SSurfLvl2 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl2_MP2S"
    arcpy.management.MultipartToSinglepart(in_features=SurfLvl2_Dissolve, out_feature_class=MP2SSurfLvl2)

    # Process: ResplitSurfLvl2 (Split Line at Point) (management)
    SpliAtPointSurfLvl2 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl2_Resplit"
    arcpy.management.SplitLineAtPoint(in_features=MP2SSurfLvl2, point_features=FWY_FV2PEndpointsCount_3Plus, out_feature_class=SpliAtPointSurfLvl2, search_radius="0.1 Meters")

    # Process: MakeFL SurfLvl3 (Make Feature Layer) (management)
    FL_SurfLvl3 = "FL_SurfLvl3"
    arcpy.management.MakeFeatureLayer(in_features=UTRANS_Roads_Edit_Simple, out_layer=FL_SurfLvl3, where_clause="VERT_LEVEL NOT IN ('1', '2', '0') And DOT_FCLASS IN ('Local', 'Major Collector', 'Minor Arterial', 'Minor Collector', 'Principal Arterial') And (COUNTY_L IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045') Or COUNTY_R IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045'))")

    # Process: Dissolve SurfLvl3 (Dissolve) (management)
    SurfLvl3_Dissolve = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl3_Dissolve"
    arcpy.management.Dissolve(in_features=FL_SurfLvl3, out_feature_class=SurfLvl3_Dissolve, multi_part="MULTI_PART")

    # Process: MP2S SurfLvl3 (Multipart To Singlepart) (management)
    MP2SSurfLvl3 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl3_MP2S"
    arcpy.management.MultipartToSinglepart(in_features=SurfLvl3_Dissolve, out_feature_class=MP2SSurfLvl3)

    # Process: ResplitSurfLvl3 (Split Line at Point) (management)
    SpliAtPointSurfLvl3 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl3_Resplit"
    arcpy.management.SplitLineAtPoint(in_features=MP2SSurfLvl3, point_features=FWY_FV2PEndpointsCount_3Plus, out_feature_class=SpliAtPointSurfLvl3, search_radius="0.1 Meters")

    # Process: MakeFL SurfLvl1 (Make Feature Layer) (management)
    FL_SurfLvl1 = "FL_SurfLvl1"
    arcpy.management.MakeFeatureLayer(in_features=UTRANS_Roads_Edit_Simple, out_layer=FL_SurfLvl1, where_clause="VERT_LEVEL NOT IN ('0', '2', '3') And DOT_FCLASS IN ('Local', 'Major Collector', 'Minor Arterial', 'Minor Collector', 'Principal Arterial') And (COUNTY_L IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045') Or COUNTY_R IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045'))")

    # Process: Dissolve SurfLvl1 (Dissolve) (management)
    SurfLvl1_Dissolve = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl1_Dissolve"
    arcpy.management.Dissolve(in_features=FL_SurfLvl1, out_feature_class=SurfLvl1_Dissolve, multi_part="MULTI_PART")

    # Process: MP2S SurfLvl1 (Multipart To Singlepart) (management)
    MP2SSurfLvl1 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl1_MP2SP"
    arcpy.management.MultipartToSinglepart(in_features=SurfLvl1_Dissolve, out_feature_class=MP2SSurfLvl1)

    # Process: ResplitSurfLvl1 (Split Line at Point) (management)
    SpliAtPointSurfLvl1 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl1_Resplit"
    arcpy.management.SplitLineAtPoint(in_features=MP2SSurfLvl1, point_features=FWY_FV2PEndpointsCount_3Plus, out_feature_class=SpliAtPointSurfLvl1, search_radius="0.1 Meters")

    # Process: MakeFL SurfLvl0 (Make Feature Layer) (management)
    FL_SurfLvl0 = "FL_SurfLvl0"
    arcpy.management.MakeFeatureLayer(in_features=UTRANS_Roads_Edit_Simple, out_layer=FL_SurfLvl0, where_clause="VERT_LEVEL NOT IN ('1', '2', '3') And DOT_FCLASS IN ('Local', 'Major Collector', 'Minor Arterial', 'Minor Collector', 'Principal Arterial') And (COUNTY_L IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045') Or COUNTY_R IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045'))")

    # Process: Dissolve SurfLvl0 (Dissolve) (management)
    SurfLvl0_Dissolve = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl0_Dissolve"
    arcpy.management.Dissolve(in_features=FL_SurfLvl0, out_feature_class=SurfLvl0_Dissolve, multi_part="MULTI_PART")

    # Process: MP2S SurfLvl0 (Multipart To Singlepart) (management)
    MP2SSurfLvl0 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl0_MP2SP"
    arcpy.management.MultipartToSinglepart(in_features=SurfLvl0_Dissolve, out_feature_class=MP2SSurfLvl0)

    # Process: ResplitSurfLvl0 (Split Line at Point) (management)
    SpliAtPointSurfLvl0 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\SurfLvl0_Resplit"
    arcpy.management.SplitLineAtPoint(in_features=MP2SSurfLvl0, point_features=FWY_FV2PEndpointsCount_3Plus, out_feature_class=SpliAtPointSurfLvl0, search_radius="1 Meters")

    # Process: MakeFL FwyLvl0 (Make Feature Layer) (management)
    FL_FwyLvl0 = "FL_FwyLvl0"
    arcpy.management.MakeFeatureLayer(in_features=UTRANS_Roads_Edit_Simple, out_layer=FL_FwyLvl0, where_clause="VERT_LEVEL NOT IN ('1', '2', '3') And (DOT_FCLASS IN ('Interstate', 'Other Freeway') Or DOT_RTNAME LIKE '%C%' Or DOT_RTNAME LIKE '%R%') And (COUNTY_L IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045') Or COUNTY_R IN ('49003', '49003', '49011', '49035', '49049', '49057', '49045'))")

    # Process: Dissolve FwysLvl0 (Dissolve) (management)
    DisFwysLvl0 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel0_Dissolve"
    arcpy.management.Dissolve(in_features=FL_FwyLvl0, out_feature_class=DisFwysLvl0, multi_part="MULTI_PART")

    # Process: MP2S FwysLvl0 (Multipart To Singlepart) (management)
    MP2SFwyLv0 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel0_MP2SP"
    arcpy.management.MultipartToSinglepart(in_features=DisFwysLvl0, out_feature_class=MP2SFwyLv0)

    # Process: ResplitFwyLvl0 (Split Line at Point) (management)
    SpliAtPointFwyLvl0 = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\FWYLevel0_Resplit"
    arcpy.management.SplitLineAtPoint(in_features=MP2SFwyLv0, point_features=FWY_FV2PEndpointsCount_3Plus, out_feature_class=SpliAtPointFwyLvl0, search_radius="0.1 Meters")

    # Process: Copy Features (Copy Features) (management)
    FwysLvl0_SchemaSeed_ = "C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb\\RCL2TDMGeometry"
    arcpy.management.CopyFeatures(in_features=SpliAtPointFwyLvl0, out_feature_class=FwysLvl0_SchemaSeed_)

    # Process: Append (Append) (management)
    CandidateTDMRoadLinks, Appended_Row_Count, Updated_Row_Count = arcpy.management.Append(inputs=[SpliAtPointFwyLvl2, SpliAtPointFwyLvl3, SpliAtPointFwyLvl1, SpliAtPointSurfLvl2, SpliAtPointSurfLvl3, SpliAtPointSurfLvl1, SpliAtPointSurfLvl0], target=FwysLvl0_SchemaSeed_, schema_type="NO_TEST", field_mapping="")

    # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) (management)
    RCL2TDMGeometry = arcpy.management.CalculateGeometryAttributes(in_features=CandidateTDMRoadLinks, geometry_property=[["MIDX", "INSIDE_X"], ["MIDY", "CENTROID_Y"]], coordinate_system="PROJCS[\"NAD_1983_UTM_Zone_12N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-111.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")[0]

    # Process: Add Field (Add Field) (management)
    RCL2TDMGeometry_2_ = arcpy.management.AddField(in_table=RCL2TDMGeometry, field_name="MidPointID", field_type="TEXT", field_length=30)[0]

    # Process: Calculate Field (Calculate Field) (management)
    RCL2TDMGeometry_3_ = arcpy.management.CalculateField(in_table=RCL2TDMGeometry_2_, field="MidPointID", expression="str(int(!midx!)) + \"|\" + str(int(!midy!)) ")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb", workspace="C:\\Users\\bgranberg\\Documents\\ArcGIS\\Projects\\FunctionalClassEditsApril\\Default.gdb"):
        RCLmerge()
